// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJiW6zkOfd-Gx0oUEYBjMLWQU8uzBisCo',
    appId: '1:987883187065:web:b2280211756bada0fedda8',
    messagingSenderId: '987883187065',
    projectId: 'water-reminder-new',
    authDomain: 'water-reminder-new.firebaseapp.com',
    storageBucket: 'water-reminder-new.firebasestorage.app',
    measurementId: 'G-5JJ738NREH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8nQkNV0luksuZ7jfXbMmhYWGQBvnV_yk',
    appId: '1:987883187065:android:7baa3a7f8a3be80dfedda8',
    messagingSenderId: '987883187065',
    projectId: 'water-reminder-new',
    storageBucket: 'water-reminder-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj9A3zkMpIEEvanAT0NJORJz_CdozvyGU',
    appId: '1:987883187065:ios:b8d32e5f497814dafedda8',
    messagingSenderId: '987883187065',
    projectId: 'water-reminder-new',
    storageBucket: 'water-reminder-new.firebasestorage.app',
    iosBundleId: 'com.example.miniProWaterReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj9A3zkMpIEEvanAT0NJORJz_CdozvyGU',
    appId: '1:987883187065:ios:b8d32e5f497814dafedda8',
    messagingSenderId: '987883187065',
    projectId: 'water-reminder-new',
    storageBucket: 'water-reminder-new.firebasestorage.app',
    iosBundleId: 'com.example.miniProWaterReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJiW6zkOfd-Gx0oUEYBjMLWQU8uzBisCo',
    appId: '1:987883187065:web:ac83b4b7f4f5c27efedda8',
    messagingSenderId: '987883187065',
    projectId: 'water-reminder-new',
    authDomain: 'water-reminder-new.firebaseapp.com',
    storageBucket: 'water-reminder-new.firebasestorage.app',
    measurementId: 'G-WYVV7P7D63',
  );
}
